export const MINUTE_IN_SECONDS = 60;
export const HOUR_IN_SECONDS = 60 * MINUTE_IN_SECONDS;
export const DAY_IN_SECONDS = 24 * HOUR_IN_SECONDS;
export const WEEK_IN_SECONDS = 7 * DAY_IN_SECONDS;
export const MONTH_IN_SECONDS = 30 * DAY_IN_SECONDS;
export const YEAR_IN_SECONDS = 365 * DAY_IN_SECONDS;

export const SECOND_IN_MILISECONDS = 1000;
export const MINUTE_IN_MILISECONDS = MINUTE_IN_SECONDS * SECOND_IN_MILISECONDS;
export const HOUR_IN_MILISECONDS = HOUR_IN_SECONDS * SECOND_IN_MILISECONDS;
export const DAY_IN_MILISECONDS = DAY_IN_SECONDS * SECOND_IN_MILISECONDS;
export const WEEK_IN_MILISECONDS = WEEK_IN_SECONDS * SECOND_IN_MILISECONDS;
export const MONTH_IN_MILISECONDS = MONTH_IN_SECONDS * SECOND_IN_MILISECONDS;
export const YEAR_IN_MILISECONDS = YEAR_IN_SECONDS * SECOND_IN_MILISECONDS;
